### ISSUE TITLE
same as #11 tiktok-scraper: command not found

### ISSUE THREAD

**Issue by tallevy22** [bellingcat/tiktok-hashtag-analysis#12]
the program recognize the parameters sent hashtag london and paris, creates the data folder but returns tiktok scrape command not found
subprocess.CalledProcessError: Command 'tiktok-scraper hashtag london -t 'json' --filepath /var/folders/k0/mrsr8fr91856s9bpr07tk32w0000gn/T/tmpw5plbags' returned non-zero exit status 127.
python-BaseException

**Comment by binlabs** [comment]
I've added a response to to Issue #11 that should help you.

**Comment by trislee** [comment]
Switched to working scraper in commit https://github.com/bellingcat/tiktok-hashtag-analysis/commit/900d6adc69f1e59cc9c405dcbf4792f36f6960c8. This should solve your problem, let me know if you still have issues running the tool.
