### ISSUE TITLE
Error: Non-zero exit status 1

### ISSUE THREAD

**Issue by meatballhead99** [bellingcat/tiktok-hashtag-analysis#13]
Ran through all the steps of the scraper and when I got to this command (python3 run_downloader.py -t ukraine -p) I got a process error,  non-zero exit status 1.

Does anyone know why this would be? 

I had run a couple of other commands today with a different TikTok scraper which were successful.

**Comment by alksndrrrr** [comment]
Hey, which tiktok scraper did you have success with? This one seems to be broken because its using that drawrowfly tiktok scraper api which is outdated. I just want to scrape some hashtags and none of this stuff works

**Comment by meatballhead99** [comment]
Hey, I was using a TikTok trending hashtag scraper from drawrowfly (https://github.com/drawrowfly/tiktok-scraper), the script ending in .hashtag, I think it all worked for me in the end. My issue ended up being that the hashtag I was trying to scrape was removed from TikTok

**Comment by trislee** [comment]
We're using a native Python scraper now, so there shouldn't be any errors when no hashtags are downloaded. Let us know if you have any issues using the tool.
