### ISSUE TITLE
Limiting number of video downloads

### ISSUE THREAD

**Issue by megler** [bellingcat/tiktok-hashtag-analysis#9]
It doesn't appear there is a built in function to limit the number of video downloads. I've been looking through the code. Where would be a good place to put a limiter or is it there and I missed it?

**Comment by megler** [comment]
I have it. For anyone who wants a fast fix, go into file_methods.py and into the download_videos function. Find:

`tiktok_command = f"tiktok-scraper hashtag {tag} -d --filepath {path}"`

and change to:

`tiktok_command = f"tiktok-scraper hashtag {tag} -d -n 5 --filepath {path}"`  <-- Where "5" is the number you want to limit your downloads to.

I've actually added a parser argument and updated the code so you can define your download limit on the command line.

`python3 run_downloader.py -t london  -v -n 2`  <-- Where -n 2 defines your download limit.

If you're interested, let me know and I'll be happy to provide the code update.

**Comment by trislee** [comment]
Yes, feel free to submit a pull request!

**Comment by megler** [comment]
All set.

**Comment by trislee** [comment]
Implemented in https://github.com/bellingcat/tiktok-hashtag-analysis/commit/6fa1e5026c5667b6d14ec1bc515f01d70ff3fc6e with `--limit` argument
